### ISSUE TITLE
The option `self` does not exist - when attempting to add a new top-level flake output and leveraging it

### ISSUE THREAD

**Issue by x10an14** [hercules-ci/flake-parts#117]
Hi!

I'm trying to make a top-level flake output variable `allowedUnfreePackages`, which I intend to reference through the `self` parameter made/created for me by `flake-parts`.

I already leverage the `self` parameter in my module system (see previous commits of below branch), so that works fine.
I do not understand the error message though, as `self` obviously exists. Why does it think it's an option?

(I have tried with assigning a `inputs.nixpkgs.lib.option` to the top-level flake output variable instead, but I got nowhere with that avenue of attack).

My attempt can be found in the HEAD commit of this branch: https://git.sr.ht/~x10an14/nix-configs/log/global-unfree-predicate

**Comment by roberth** [comment]
`self` is only a module argument, not an option, let alone an option you can define a value for. The value of `self` comes directly from Nix.

In order to make your `allowedUnfreePackages` global, it doesn't have to be in `flake`, but you do have to declare it, as it seems that you want to merge definitions from multiple places.

What you're trying to solve is not a unique problem though. I think the right solution is to have a better nixpkgs module, and perhaps also a home manager module that integrates with the `pkgs` constructed by that nixpkgs module.

Refs #74

**Comment by x10an14** [comment]
I [solved it without flake-parts](https://git.sr.ht/~x10an14/nix-configs/commit/97a89b104184d3ccc3bf0e7af9c124aa6427c646) for now. Subscribed to #74 for progress updates.

Ideally, I wish to assign this `allowedUnfreePackages` option to a flake-global variable, instead of `config`.
(Due `config` only being available after `home-manager.lib.homeManagerConfiguration` or `nixpkgs.lib.nixosSystem` invocations).

**Comment by roberth** [comment]
Aren't you invoking those functions from within a scope that has the flake-parts `config`? You could then forward it.

I'll close this, but feel free to ask questions.

**Comment by x10an14** [comment]
> (...) I'll close this, but feel free to ask questions.

Thanks!
> Aren't you invoking those functions from within a scope that has the flake-parts `config`? You could then forward it.

I already tried asking for guidance/help with that over at [your Matrix channel](https://matrix.to/#/!gcrYWdPsIUOFpXFDHB:matrix.org/$2kpjmEEa-2WbBH2ZQbonZjyTGXt1gfpFSGMQjrWCU-k?via=matrix.org&via=nixos.dev&via=maralorn.de), but I didn't feel comfortable continuing the discussion to be honest.

I felt there was too much of a disconnect between the respective perspectives of the ones in the know, and the newbie who knows next to nothing (me). It didn't make me feel as if I could ask for help without becoming too much of a bother.

To be clear; I suspect no ill will - a lot gets missed/misunderstood with written chat.
I just didn't feel like it was possible to communicate due to lack of what I'd call a "common platform of understanding".

---

I still do not understand the differences/similarities/intricacies of `config` from within the contexts of the referenced function invocations [here](https://github.com/hercules-ci/flake-parts/issues/117#issuecomment-1418110195), and the `config.flake` mentioned in your documentation. I have no idea what I don't understand, which makes it nigh impossible for me to know what questions to ask, let alone how to formulate them correctly.

(And this from a ~2yrs nix(os) user who has experience from writing and using of options with the nixos/home-manager `config` specialArgs variable).

I just know that at some times/places these are different `configs`, and at others they are not. Not really managed to find examples showing this interplay between them/how to leverage `config.flake`.

**Comment by roberth** [comment]
Hi @x10an14,

The way flake-parts uses the module system is more complicated than NixOS, so don't despair :)
It seems that I've underestimated the difficulty of developing new modules. I'll make an attempt at filling in some of the missing documentation about the module system specifically.

> at some times/places these are different `configs`,

That deserves an article of its own.

**Comment by drupol** [comment]
Looking forward to it!'
