### ISSUE TITLE
Template flakes do not contain `flake-parts` as input, yet they rely on it.

### ISSUE THREAD

**Issue by Niols** [hercules-ci/flake-parts#138]
For instance, in the multi-module template (but it is the same for the others):

https://github.com/hercules-ci/flake-parts/blob/dcc36e45d054d7bb554c9cdab69093debd91a0b5/template/multi-module/flake.nix#L4-L8

Is this on purpose? I would have expected the template to contain

```
inputs.flake-parts.url = "github:hercules-ci/flake-parts";
```

**Comment by terlar** [comment]
Without that it will use the `flake-parts` from the [flake-registry](https://github.com/NixOS/flake-registry/blob/master/flake-registry.json#L92-L102), I think it is intended.

**Comment by roberth** [comment]
That is correct, but now the input is explicit, so that this question doesn't have to be asked again.
- thanks to #210
