### ISSUE TITLE
NixOS options not 1:1 available

### ISSUE THREAD

**Issue by keidrych** [hercules-ci/flake-parts#179]
I'm on NixOS 23.05, and one of the changes was _fonts.fonts_ became _fonts.packages_
additionally _fonts.enableDefaultPackages_ also triggers an error

There are no errors when using flakes normally
with flake-parts, the following error occurs, the same if _fonts.packages_ is used

```
error: The option `fonts.enableDefaultPackages' does not exist. Definition values:
       - In `/nix/store/fckpbv0vcld0h7j30540zwa8ji6d4gd1-source/flake.nix#nixosModules.default': true
```

It appears that flake-parts doesn't have access to the new options configuration used in 23.05 & is using the 22.11 or older options?

Below is code to reproduce this issue
```
{
  description = "LeFailure";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
    flake-parts = {
      url = "github:hercules-ci/flake-parts";
    };
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } (top@{ moduleWithSystem, withSystem, ... }: {
      imports = [ ];
      systems = [ "x86_64-linux" ];
      flake = {
        nixosModules.default = moduleWithSystem
          (
            perSystem@{ config }: # NOTE: only explicit params will be in perSystem
            nixos@{ pkgs, ... }:
            {
              fonts = {
                fontDir.enable = true;
                enableDefaultPackages = true;
                packages = with pkgs; [
                  fira-code
                ];
              };
              imports = [
                ./configuration.nix
                ./hardware-configuration.nix
              ];
            }
          );

        nixosConfigurations.default = withSystem "x86_64-linux"
          (ctx@{ config, inputs', ... }:
            inputs.nixpkgs.lib.nixosSystem {
              specialArgs = inputs;
              modules = [
                top.config.flake.nixosModules.default
              ];
            }
          );
      };
    });
```

**Comment by roberth** [comment]
> fonts.enableDefaultPackages

This seems to have been introduced after 23.05 when I look it up in search.nixos.org.
- [unstable](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=fonts.enableDefaultPackages): found
- [23.05](https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=fonts.enableDefaultPackages): not found

**Comment by roberth** [comment]
These releases are not supported anymore, and when you're doing `inputs.nixpkgs.lib.nixosSystem` in the example above there's really no way you don't get a NixOS from the Nixpkgs you specified in `inputs` at the top. If it does, it'd be a Nix bug.
My earlier comment suggests a more plausible mechanism for the observations.
I'll assume this is resolved, but I'll reopen this if you still experience a problem like this.
