### ISSUE TITLE
nix flake show broken

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/flake-parts#195]
```shell-session
$ git clone https://github.com/OceanSprint/pydev.git && cd pydev
$ nix flake show --json
{"flakeModule":{"type":"unknown"}}
```

**Comment by phaer** [comment]
I believe that's expected behavior without something like [flake schemas](https://determinate.systems/posts/flake-schemas), as nix itself doesn't know anything about flakeModule(s) outputs?

**Comment by domenkozar** [comment]
Ohh my bad, I see that the only thing it exports is the module.
