### ISSUE TITLE
How to define a custom flake attribute for a reusable module

### ISSUE THREAD

**Issue by loqusion** [hercules-ci/flake-parts#201]
I'm trying to add a custom option `lib` to my reusable flake module, and here's [what the documentation has to say about it](https://flake.parts/define-custom-flake-attribute#how-do-i-do-it) (emphasis added):

> If your custom output attribute is a one-off because you need to do something special in a single project, all you have to do is define a value in the [flake option](https://flake.parts/options/flake-parts#opt-flake).
>
> **However, if you want it to be reusable and integrate well, you should _declare an option_ for it**, and you could perhaps provide a bit of support logic if that makes sense to do.

However, this piece of documentation does not answer the question "how do I _declare an option_?", nor does it provide a link doing so. Looking through the rest of the documentation also does not provide any obvious answers.

It would be very helpful if a link that answers this question were present in this text, something like:

> If your custom output attribute is a one-off because you need to do something special in a single project, all you have to do is define a value in the [flake option](https://flake.parts/options/flake-parts#opt-flake).
>
> However, if you want it to be reusable and integrate well, you should [declare an option](https://github.com) for it, and you could perhaps provide a bit of support logic if that makes sense to do.

Or, alternatively, provide a code snippet that demonstrates how to do so.

**Comment by bew** [comment]
Why close? Did you find documentation?
I'm kinda blocked as well around this topic of "how to actually do a module"

**Comment by loqusion** [comment]
The next section in the documentation [links here](https://github.com/hercules-ci/flake-parts/blob/main/modules/packages.nix), which kinda shows how you can add custom `perSystem` attributes to a flake, but I've tried multiple different combinations and none of them worked for me. I ended up just defining my own `eachSystem` utility instead of using `flake-parts`.

As for why I closed the issue, part of me fears the backlash from attacking the hegemony of those with a deep understanding of nix who have a vested interest in not making nix easier to use for the layman in order to bolster their own power relative to everyone else (not that I squarely place the blame on them).

**Comment by terlar** [comment]
This shows an example on how to define a custom option that will put things under the root flake.

https://github.com/hercules-ci/flake-parts/blob/main/modules/nixosModules.nix#L14

You can use the `mkSubmoduleOptions` from `flake-parts-lib`.
