### ISSUE TITLE
self' is not per system?

### ISSUE THREAD

**Issue by zimbatm** [hercules-ci/flake-parts#22]
When I try to remove the `rec`, I get infinite recursion. Is `self'` not supposed to be a reference of the config per system?
```diff
diff --git a/flake.nix b/flake.nix
index 6bb90e1..1375701 100644
--- a/flake.nix
+++ b/flake.nix
@@ -14,13 +14,13 @@
   outputs = { self, flake-parts, ... }:
     flake-parts.lib.mkFlake { inherit self; } {
       systems = [ "x86_64-linux" ];
-      perSystem = { system, ... }: rec {
+      perSystem = { self', system, ... }: {
         legacyPackages = import ./. { inherit system; };
 
         # For garnix
-        checks = legacyPackages._flatten { };
+        checks = self'.legacyPackages._flatten { };
 
-        devShells.default = legacyPackages.devshell;
+        devShells.default = self'.legacyPackages.devshell;
       };
     };
 }
```

**Comment by roberth** [comment]
`self'` goes through Nix's flake wiring whereas you could use `config`, which contains essentially the same information, unless you're doing something to the outputs outside of `mkFlake` (which you're not).

Maybe the module system induces a dependency that we don't expect. `--show-trace` may reveal that.

**Comment by srid** [comment]
@roberth I just got `infinite recursion encountered` when using a `flake-parts` module. It happens when evaluating `self.callCabal2nix` (note: this is a different 'self') from inside haskell overrides: https://github.com/srid/emanote/pull/290#issuecomment-1141187436

(Full trace is in that link)

I'm trying to debug this. Let me know if you have any hints!

**Comment by roberth** [comment]
@srid Another cause could be the use of `attrsOf`. `lazyAttrsOf` is a safer default in flake modules, as they tend to be a bit more cyclical than your average NixOS configuration setting. My bad because I mentioned `attrsOf` in a review.

**Comment by srid** [comment]
Aha, laziness! `lazyAttrsOf` did the trick, thanks!

(It is as if `type =` is hacky way to *declare* types in Nix, and these types do change the behaviour of the expressions.).

**Comment by roberth** [comment]
That's how it seems, but types are also functions (from value to value) and monoid instances. Funky stuff ensues.

**Comment by roberth** [comment]
The original issue seems to have been resolved by removing uses of `filterAttrs` and `attrsOf` (as opposed to `lazyAttrsOf`) and/or defining more options.
If some infinite recursion still occurs, I'm going to need an example to debug it. That'd best be done in a new issue.
