### ISSUE TITLE
Use mdbook for site

### ISSUE THREAD

**Issue by roberth** [hercules-ci/flake-parts#31]
_Should_ be feasible as the options generation is already using pandoc instead of docbook's own tooling. Wouldn't mind doing more ugly stuff either, if necessary.

**Comment by srid** [comment]
I'd shamelessly plug [Emanote](https://emanote.srid.ca/) 😁 but `mdBook` is a fine choice as well.

**Comment by roberth** [comment]
I thought of mdBook because it appears to have some momentum. I've been using mostly `antora` (advanced asciidoc) in recent times.

I'm inclined to go with something simple. I like mdBook's search capability and minimalist look. Not having search is probably a dealbreaker because I want to categorize the options by repo, yet still have a search capability for all of them together.

**Comment by zimbatm** [comment]
@roberth feel free to steal https://github.com/numtide/devshell/blob/master/modules/modules-docs.nix

**Comment by roberth** [comment]
@zimbatm Thanks!

For now the docs are in docbook, which is kind of the standard for the module system. I'd like to migrate all module system applications to either markdown or something flexible and I figured my current solution might provide some of the ingredients for that. Here's my secret plan https://github.com/NixOS/nixpkgs/issues/175586.

**Comment by roberth** [comment]
Done in #68
