### ISSUE TITLE
arbitrary keys  with perSystem?

### ISSUE THREAD

**Issue by edrex** [hercules-ci/flake-parts#34]
I'm converting a project using flake-utils, which has `outputs.${system}.lib` (lib needs system for.. reasons). `flake-utils.lib.eachDefaultSystem` is open to whatever keys you return, but `flake-parts.lib.mkFlake`'s `perSystem` attr doesn't accept attrs that don't correspond to a module's option definition. Talking through this myself, I wonder if I'm supposed to create a module that defines a `lib` option?

**Comment by srid** [comment]
I'm curious about this too. It seems to be required to implement https://github.com/srid/haskell-flake/issues/12

**Comment by roberth** [comment]
> `outputs.${system}.lib`

This is non-standard, so it is not something for `flake-parts` itself to define.
I'd go with `outputs.lib.${system}` instead, as `lib` has a better chance of being accepted by `nix flake check` at some point. I don't expect the `${system}` attribute to become standard under `lib`, but you'll be free to use it that way anyway.

> create a module that defines a `lib` option?

Yes, you could do this. Here's an example of a module that similarly adds a `packages` attribute to the flake outputs. You could adapt that for `lib`. https://github.com/hercules-ci/flake-parts/blob/main/modules/packages.nix

**Comment by edrex** [comment]
I guess what I'm still missing is how to set an arbitrary per-system attribute `outputs.foo.${system} = "bar"` similar to `flake.baz = "ban"` in `mkFlake`.

**Comment by edrex** [comment]
I see that modules/packages.nix has a `mapAttrs` that does this, so I guess there's no syntax sugar for it.
