### ISSUE TITLE
Enable discussions on repo?

### ISSUE THREAD

**Issue by edrex** [hercules-ci/flake-parts#36]
It seems like a GH Discussions instance on flake-parts could be a good place to share ideas and collaboratively solve design problems. Can haz discussions tab? @roberth 

Specifically, I came today with thoughts about how it might be possible to utilize large parts of the NixOS module library in a cross-platform way, by providing "polyfills" (injected alternative implementations) for some key modules and utility functions (such as the systemd module for managing service instances).

**Comment by roberth** [comment]
Done.

> utilize large parts of the NixOS module library

You may also be interested in https://github.com/NixOS/nixpkgs/pull/148456, as utilizing _small_ parts is the start of utilizing large parts.

**Comment by edrex** [comment]
Hey, it sounds like you're already looking in that direction. Awesome! I really like the idea of segmenting the NixOS module library up into different API namespaces, like nixos.core, that have different constraints on the environment. It would be amazing to be able to deploy a nixos service module using a flake on macos using some compatibility layer, etc. I'll take a closer look at the linked issues etc and try to catch up.
