### ISSUE TITLE
Provide explanation for usage of `pkgs.nixos` instead of `lib.nixosSystem`

### ISSUE THREAD

**Issue by montchr** [hercules-ci/flake-parts#47]
I hadn't encountered `pkgs.nixos` before seeing it in one of the examples here. I'm more accustomed to seeing `lib.nixosSystem` everywhere else.

What's the reasoning for choosing `pkgs.nixos` over `lib.nixosSystem` in the context of this project? Is there any reason to avoid the latter when creating a system config based on this library?

I suspect I am not alone in this confusion. Could you add an explanation/expansion to the example please?

FWIW I had a lot of difficulty tracking down its source. search.nixos.org doesn't seem to find it, and `pkgs.nixos` is pretty hard to search for in general without many false positives. I finally managed to track it down in `all-packages.nix`, where it's defined. This is a pretty arcane source, especially since the file is 1.1MB -- too big for GitHub to display, and AFAIK not possible to link to directly...

https://raw.githubusercontent.com/NixOS/nixpkgs/nixos-22.05/pkgs/top-level/all-packages.nix

**Comment by roberth** [comment]
It's a bit more efficient, reusing the Nixpkgs invocation it is part of. Eelco doesn't like functions like it https://github.com/NixOS/nixpkgs/pull/47684#issuecomment-439097274, but we still don't have an alternative for functions that have `pkgs` in their closure, and it's so convenient... and part of my muscle memory. It predates flakes actually.
You could achieve the same kind of thing with `lib.nixosSystem`, but you'll need an extra line to assign `pkgs` in its configuration.

**Comment by roberth** [comment]
Perhaps we should change it to `nixosSystem`, because `nixos` doesn't support `specialArgs`.

I'd recommend to avoid `specialArgs` because it's a global-ish namespace which is bad for composition, but `flake-parts`' goal is to make things interoperable, not to impose opinions. This aspect of `specialArgs` comes into play when you create `nixosModules` for use outside the defining flake.

**Comment by montchr** [comment]
Thanks for clarifying!

Coincidentally, I was also wondering about the use of `_module.args` and not `specialArgs`, which I think you also addressed above.

I assumed, wrongfully I think, that the underscore prefix indicated that the `_module` attributes were for private use in the internals of the module system and that the un-prefixed `specialArgs` was more part of a public API, so to speak.
