### ISSUE TITLE
How to use rosetta on M1?

### ISSUE THREAD

**Issue by srid** [hercules-ci/flake-parts#50]
What's the most idiomatic way to configure flake-parts so that the `pkgs` of `perSystem` (and other relevant places) uses x86_64-darwin *if* on aarch64-darwin?

Currently I pass `--option system x86_64-darwin` to nix commands; but can this obviated when using flake-parts?

**Comment by shanesveller** [comment]
I've been using something like:
```nix
{ inputs, lib, self, ... }:
let
  overlays = {
    # ...
    rosettaPackages = final: prev:
      lib.attrsets.genAttrs [ "cargo-watch" "watchexec" "wrk" ]
        (name: inputs.nixpkgs.legacyPackages.x86_64-darwin.${name});
  };
in {
  flake = { inherit overlays; };

  perSystem = { lib, system, ... }:
    let
      pkgs = import inputs.nixpkgs {
        config = {
          # ...
        };
        overlays = [
          # ...
        ] ++ lib.optional (system == "aarch64-darwin") overlays.rosettaPackages;
        inherit system;
      };
    in { config = { _module.args.pkgs = pkgs; }; };
}
```

I'd love to make the actual list of packages more readily configurable.

**Comment by roberth** [comment]
You _could_ forcibly define `pkgs` yourself based on the `system` module argument.

```nix
{
  perSystem = { config, lib, system, pkgs, ... }: {
    _module.args.pkgs = lib.mkForce (import nixpkgs { system = f system; });
  };
}
```

where `f` can be any logic you want. However, I think you _should not_.

My interpretation of the flake `system` is that it should match the `hostPlatform`: the platform where an executable is intended to run. This is backed up by Eelco's comment that `system` is defined by how Nix uses it, which is usually to run an executable. 

Returning an x86_64 executable in an `aarch64-darwin` will be problematic for os installations without rosetta. This is not a problem when you use `--option system x86_64-darwin`.

Perhaps the `nix` could read the `ARCHPREFERENCE` environment variable, or something similar, to select the right `system` automatically?

What is the specific problem you are working around?

**Comment by roberth** [comment]
@shanesveller's solution seems like a good workaround for when some development tools are not available for the native arch. Making assumptions about the developer os is not as bad as making those assumptions about the user os in attributes such as `packages`.

**Comment by shanesveller** [comment]
> What is the specific problem you are working around?

In my case it's simply that some packages won't build on aarch64 (varying over time per the nixpkgs input) but will seemingly run as intended with an x86_64 binary. I only use the technique under duress when I don't have time to triage a broken build in nixpkgs.

**Comment by srid** [comment]
That makes sense. My use-case is to work with PureScript projects; see https://github.com/purs-nix/purs-nix/issues/17

A proper fix is to limit Rosetta to the requisitive packages (here `purescript`), while using native for the rest, as @shanesveller's solution illustrates. The main challenge with the overrides approach is that `purescript-tools` [fetches prebuilt binaries](https://github.com/purs-nix/purescript-tools/blob/master/purescript/0.15.4.nix), instead of using nixpkgs derivation. I'll think about it more.

**Comment by srid** [comment]
For those that are reading this issue, I ended up customizing `system` narrowly for `purs-nix` alone. The associated `flake-parts` module has these:

```nix
      purs-nix-system = lib.mkOption {
        type = lib.types.str;
        # Use rosetta on M1, as purs-nix doesn't support it natively yet.
        default = if system == "aarch64-darwin" then "x86_64-darwin" else system;
      };
      purs-nix = lib.mkOption {
        type = lib.types.unspecified;
        default = self.inputs.purs-nix { system = config.purs-nix-system; };
      };
      ps-tools = lib.mkOption {
        type = lib.types.unspecified;
        default = inputs.ps-tools.legacyPackages.${config.purs-nix-system};
      };
```
